const {Movies} = require('../models')


// G: 1
// PG: 2
// PG-13: 3
// R: 4
// NC-17: 5



const movieData = [
    {
        title: 'The Blair Witch Project',
        director: 'Daniel Myrick, Eduardo Sánchez',
        genre: 'the woods',
        rating: '4',
        release_year: 1999,
        description: 'Three film students vanish after traveling into a Maryland forest to film a documentary on the local Blair Witch legend, leaving only their footage behind.',
        poster_url: "https://m.media-amazon.com/images/M/MV5BNzQ1NDBlNDItMDAyYS00YTI2LTgwMmYtMzAwMzg4NDFlM2ZmXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    },

    {
        title: 'Wrong Turn',
        director: 'Mike P. Nelson',
        genre: 'the woods',
        rating: '4',
        release_year: 2021,
        description: 'Friends hiking the Appalachian Trail are confronted by "The Foundation", a community of people who have lived in the mountains for hundreds of years.',
        poster_url: "https://m.media-amazon.com/images/M/MV5BMTQwMTkyMTY4M15BMl5BanBnXkFtZTYwMDc0NDE3._V1_SX300.jpg",
    },

    {
        title: 'Dead End',
        director: 'Jean-Baptiste Andrea, Fabrice Canepa',
        genre: 'the woods',
        rating: '4',
        release_year: 2023,
        description: 'Christmas Eve. On his way to his in-laws with his family, Frank Harrington decides to try a shortcut, for the first time in 20 years. It turns out to be the biggest mistake of his life.',
        poster_url: "https://m.media-amazon.com/images/M/MV5BNTM2YWZhMjktMDk5My00YzMxLTk5ZDAtNmM0NTkyMDZmMWE2XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    },
    {
        title: 'Friday the 13th',
        director: 'Sean S. Cunningham',
        genre: 'the woods',
        rating: '4',
        release_year: 1980,
        description: 'A group of camp counselors trying to reopen a summer camp called Crystal Lake, which has a grim past, are stalked by a mysterious killer.',
        poster_url: "https://m.media-amazon.com/images/M/MV5BNWMxYTYzYWQtNGZmNy00MTg5LTk1N2MtNzQ5NjQxYjQ5NTJhXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    },
    {
        title: 'The Ritual',
        director: 'David Bruckner',
        genre: 'the woods',
        rating: '4',
        release_year: 1997,
        description: 'A group of old college friends reunite for a trip to a most dangerous country in Europe - Sweden, encountering a menacing presence there stalking them.',
        poster_url: "https://m.media-amazon.com/images/M/MV5BMjAzMzAyMDI4Ml5BMl5BanBnXkFtZTgwODMwOTY2NDM@._V1_SX300.jpg",
    },
    {
        title: 'The Evil Dead',
        director: 'Sam Raimi',
        genre: 'the woods',
        rating: '5',
        release_year: 1981,
        description: 'Five friends travel to a cabin in the woods, where they unknowingly release flesh-possessing demons.',
        poster_url: "https://m.media-amazon.com/images/M/MV5BNjRmY2NmN2UtMmRlMS00Mjg2LTgwNjUtZjYyZjc0NDJjODFkXkEyXkFqcGdeQXVyNjc5NjEzNA@@._V1_SX300.jpg",
    },
    {
        title: 'The Evil Dead 2',
        director: 'Sam Raimi',
        genre: 'the woods',
        rating: '4',
        release_year: 1987,
        description: 'The lone survivor of an onslaught of flesh-possessing spirits holes up in a cabin with a group of strangers while the demons continue their attack.',
        poster_url: "https://m.media-amazon.com/images/M/MV5BMWY3ODZlOGMtNzJmOS00ZTNjLWI3ZWEtZTJhZTk5NDZjYWRjXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    },
    {
        title: 'Cabin in the Woods',
        director: 'Drew Goddard',
        genre: 'meta horror',
        rating: '4',
        release_year: 2011,
        description: 'Five friends go for a break at a remote cabin, where they get more than they bargained for, discovering the truth behind the cabin in the woods.',
        poster_url: "https://m.media-amazon.com/images/M/MV5BNTUxNzYyMjg2N15BMl5BanBnXkFtZTcwMTExNzExNw@@._V1_SX300.jpg",
    },
    
    {
        title: 'Scream',
        director: 'Wes Craven',
        genre: 'meta horror',
        rating: '4',
        release_year: 1996,
        description: 'A year after the murder of her mother, a teenage girl is terrorized by a masked killer who targets her and her friends by using scary movies as part of a deadly game.',
        poster_url: "https://m.media-amazon.com/images/M/MV5BMjA2NjU5MTg5OF5BMl5BanBnXkFtZTgwOTkyMzQxMDE@._V1_SX300.jpg",
    },
    {
        title: 'Final Girls',
        director: 'Todd Strauss-Schulson',
        genre: 'meta horror',
        rating: '3',
        release_year: 2015,
        description: 'A young woman grieving the loss of her mother, a famous scream queen from the 1980s, finds herself pulled into the world of her mom\'s most famous movie. Reunited, the women must fight off the film\'s maniacal killer.',
    },
    {
        title: 'The Thing',
        director: 'John Carpenter',
        genre: 'classics',
        rating: '4',
        release_year: 1982,
        description: 'A research team in Antarctica is hunted by a shape-shifting alien that assumes the appearance of its victims.',
        poster_url: "https://m.media-amazon.com/images/M/MV5BNGViZWZmM2EtNGYzZi00ZDAyLTk3ODMtNzIyZTBjN2Y1NmM1XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg",
    },
    {
        title: 'Dracula',
        director: 'Tod Browning, Karl Freund',
        genre: 'classics',
        rating: '',
        release_year: 1931,
        description: 'Transylvanian vampire Count Dracula bends a naive real estate agent to his will, then takes up residence at a London estate where he sleeps in his coffin by day and searches for potential victims by night.',
        poster_url: "https://m.media-amazon.com/images/M/MV5BZDQzMmIxYTItOTJkMi00YzU1LWJkNGEtYWE1NjhiNWU5YmNkXkEyXkFqcGdeQXVyNjc5NjEzNA@@._V1_SX300.jpg",
    },
    {
        title: 'Lost Boys',
        director: 'Joel Schumacher',
        genre: 'classics',
        rating: '4',
        release_year: 1987,
        description: 'After moving to a new town, two brothers discover that the area is a haven for vampires.',
        poster_url: "https://m.media-amazon.com/images/M/MV5BMWEzNmUxZTMtZjY0My00OGNmLWIyNDctODM2YzZjM2YwZWEwXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    },
    {
        title: 'Bram Stoker\'s Dracula',
        director: 'Francis Ford Coppola',
        genre: 'classics',
        rating: '4',
        release_year: 1992,
        description: 'The centuries old vampire Count Dracula comes to England to seduce his barrister Jonathan Harker\'s fiancée Mina Murray and inflict havoc in the foreign land.',
        poster_url: "https://m.media-amazon.com/images/M/MV5BNjcyMDZlMTktYTIxOC00ZWFhLWJkYzgtNWNiYjAwYTFkNjIyXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg",
    },
    {
        title: 'Candyman',
        director: 'Bernard Rose',
        genre: 'classics',
        rating: '4',
        release_year: 1992,
        description: 'The Candyman, a murderous soul with a hook for a hand, is accidentally summoned to reality by a skeptic grad student researching the monster\'s myth.',
        poster_url: "https://m.media-amazon.com/images/M/MV5BYjVjYjhlNTQtN2UxOC00Njk5LWFjNDctODNjZTI1ZGM0ZDZkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    },
    {
        title: 'The Exorcist',
        director: 'William Friedkin',
        genre: 'classics',
        rating: '4',
        release_year: 1973,
        description: 'When a young girl is possessed by a mysterious entity, her mother seeks the help of two priests to save her daughter.',
        poster_url: "https://m.media-amazon.com/images/M/MV5BYWFlZGY2NDktY2ZjOS00ZWNkLTg0ZDAtZDY4MTM1ODU4ZjljXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg",
    },
    {
        title: 'The Slumber Party Massacre',
        director: 'Amy Holden Jones',
        genre: 'classics',
        rating: '4',
        release_year: 1982,
        description: 'A female high school student\'s slumber party turns into a bloodbath, as a newly escaped psychotic serial killer wielding a power drill prowls her neighborhood.',
        poster_url: "https://m.media-amazon.com/images/M/MV5BMGIzNTMxOGEtMzg3NC00M2ZhLWEwYzAtMjE5MTQyNzBhZTcwXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    },
    {
        title: 'Black Christmas',
        director: 'Bob Clark',
        genre: 'classics',
        rating: '4',
        release_year: 1974,
        description: 'During their Christmas break, a group of sorority girls are stalked by a stranger.',
        poster_url: "https://m.media-amazon.com/images/M/MV5BYTllYWY5ZDYtZjExYy00ZTY5LTk2OWEtMTQ3NTdlNzE5NjcyXkEyXkFqcGdeQXVyMTUzMDUzNTI3._V1_SX300.jpg",
    },
    {
        title: 'Rocky Horror Picture Show',
        director: 'Jim Sharman',
        genre: 'classics',
        rating: '4',
        release_year: 1975,
        description: 'A newly-engaged couple have a breakdown in an isolated area and must seek shelter at the bizarre residence of Dr. Frank-n-Furter.',
        poster_url: "https://m.media-amazon.com/images/M/MV5BOGIzYjM3YzMtMjk5ZS00NDY2LTllMjEtNjYwZjhmMDNhMDBkXkEyXkFqcGdeQXVyODUzMjQxMTA@._V1_SX300.jpg",
    },
    {
        title: 'Rosemary\'s Baby',
        director: 'Roman Polanski',
        genre: 'meta horror',
        rating: '4',
        release_year: 1968,
        description: 'A young couple trying for a baby moves into an aging, ornate apartment building on Central Park West, where they find themselves surrounded by peculiar neighbors.',
        poster_url: "https://m.media-amazon.com/images/M/MV5BMTA5NWQwMmYtZjEyYS00Nzc2LTgwZjAtNTQ4NmFmZjNkNjg4XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg",
    },
    {
        title: 'Trick \'r Treat',
        director: 'Michael Dougherty',
        genre: 'anthologies',
        rating: '4',
        release_year: 2007,
        description: 'Five interwoven stories that occur on Halloween: an everyday high school principal has a secret life as a serial killer; a college virgin might have just met the guy for her; a group of teenagers pull a mean prank; a woman who loathes the night has to contend with her holiday-obsessed husband; and a mean old man meets his match with a demonic, supernatural trick-or-treater.',
        poster_url: "https://m.media-amazon.com/images/M/MV5BYmIyY2E5YjMtZDA3NC00MmIzLWFkZmItNzVlODllZWNlZmRkXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg",
    },
    {
        title: 'Fear Street',
        director: 'Leigh Janiak',
        genre: 'anthologies',
        rating: '4',
        release_year: 1994,
        description: 'A circle of teenage friends accidentally encounter the ancient evil responsible for a series of brutal murders that have plagued their town for over 300 years. Welcome to Shadyside.',
        poster_url: "https://m.media-amazon.com/images/M/MV5BNzQzYjIyZDQtMjBhZS00MzU3LTk0MTQtNTVmMDI3ZWY0ZWU3XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    },
    {
        title: 'V/H/S',
        director: 'Matt Bettinelli-Olpin, David Bruckner, Tyler Gillett',
        genre: 'anthologies',
        rating: '4',
        release_year: 2012,
        description: 'When a group of misfits are hired by an unknown third party to burglarize a desolate house and acquire a rare VHS tape, they discover more found footage than they bargained for.',
        poster_url: "https://m.media-amazon.com/images/M/MV5BMTUwODAxMzMwNF5BMl5BanBnXkFtZTcwMTk3MTQ5Nw@@._V1_SX300.jpg",
    },
    {
        title: 'V/H/S 2',
        director:'Simon Barrett, Jason Eisener, Gareth Evans',
        genre: 'anthologies',
        rating: '4',
        release_year: 2013,
        description: 'Searching for a missing student, two private investigators break into his house and find collection of VHS tapes. Viewing the horrific contents of each cassette, they realize there may be dark motives behind the student\'s disappearance.',
        posster_url: "https://m.media-amazon.com/images/M/MV5BODg4OTMxNDAxMV5BMl5BanBnXkFtZTcwMjM4ODQ0OQ@@._V1_SX300.jpg",
    },
    {
        title: 'Barbarian',
        director: 'Zach Cregger',
        genre: 'contemporary horror',
        rating: '4',
        release_year: 2022,
        description: 'A woman staying at an Airbnb discovers that the house she has rented is not what it seems.',
        poster_url: "https://m.media-amazon.com/images/M/MV5BN2M3Y2NhMGYtYjUxOS00M2UwLTlmMGUtYzY4MzFlNjZkYzY2XkEyXkFqcGdeQXVyODc0OTEyNDU@._V1_SX300.jpg",
    },
    {
        title: 'Broadcast Signal Intrusion',
        director: 'Jacob Gentry',
        genre: 'contemporary horror',
        rating: '',
        release_year: 2021,
        description: 'In the late 90s, a video archivist unearths a series of sinister pirate broadcasts and becomes obsessed with uncovering the dark conspiracy behind them.',
        poster_url: "https://m.media-amazon.com/images/M/MV5BNDgxYWFiY2MtYmMzMS00OWZjLTkzNTItZTkzNzEyZjQ5NjljXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    },
    {
        title: 'The Black Phone',
        director: 'Scott Derrickson',
        genre: 'contemporary horror',
        rating: '4',
        release_year: 2021,
        description: 'After being abducted by a child killer and locked in a soundproof basement, a 13-year-old boy starts receiving calls on a disconnected phone from the killer\'s previous victims.',
        poster_url: "https://m.media-amazon.com/images/M/MV5BMWQxOGJlNTUtYTc1YS00NDkyLWExZjItMTFiYWEzMjAzYTdjXkEyXkFqcGdeQXVyNjk1Njg5NTA@._V1_SX300.jpg",
    },
    {
        title: 'The Host',
        director: 'Bong Joon Ho',
        genre: 'contemporary horror',
        rating: '4',
        release_year: 2006,
        description: 'A monster emerges from Seoul\'s Han River and begins attacking people. One victim\'s loving family does what it can to rescue her from its clutches.',
        poster_url: "https://m.media-amazon.com/images/M/MV5BMTE3N2IwNmMtOGE0Ny00NWFlLTliNmUtNjY3ODExYjgxNmUyXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    },
    {
        title: 'The Fourth Kind',
        director: 'Olatunde Osunsanmi',
        genre: 'sci-fi horror',
        rating: '3',
        release_year: 2009,
        description: 'A thriller involving an ongoing unsolved mystery in Alaska, where one town has seen an extraordinary number of unexplained disappearances during the past 40 years and there are accusations of a federal cover up.',
        poster_url: "https://m.media-amazon.com/images/M/MV5BMTY2OTM0NDEyM15BMl5BanBnXkFtZTcwNTAzMDY4Mg@@._V1_SX300.jpg",
    },
    {
        title: 'Transylvania 6-5000',
        director: 'Rudy De Luca',
        genre: 'sci-fi horror',
        rating: '2',
        release_year: 1985,
        description: 'Two tabloid reporters are sent to Transylvania to find the Frankenstein monster - or get fired. They are laughed at there, but something suspicious is going on.',
        poster_url: "https://m.media-amazon.com/images/M/MV5BMjlhODIwYTAtNzFhNi00Yzg5LWE3NmYtY2I3MjY4NWNmMjhlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    },




]