[
    {
        "title": "Candyman",
        "director": "Bernard Rose",
        "genre": "remake/reboot",
        "rating": 4,
        "release_year": 1992,
        "description": "The Candyman, a murderous soul with a hook for a hand, is accidentally summoned to reality by a skeptic grad student researching the monster's myth",
    },
    {
        "title": "Evil Dead Rise",
        "director": "Lee Cronin",
        "genre": "remake/reboot",
        "rating": 4,
        "release_year": 2023,
        "description": "A twisted tale of two estranged sisters whose reunion is cut short by the rise of flesh-possessing demons, thrusting them into a primal battle for survival as they face the most nightmarish version of family imaginable",
    },
    {
        "title": "Halloween",
        "director": "John Carpenter",
        "genre": "classic",
        "rating": 4,
        "release_year": 1978,
        "description": "Fifteen years after murdering his sister on Halloween night 1963, Michael Myers escapes from a mental hospital and returns to the small town of Haddonfield, Illinois to kill again.",
    },
    {
        "title": "",
        "director": "",
        "genre": "",
        "rating": "",
        "release_year": "",
        "description": "",
    },
    {
        "title": "",
        "director": "",
        "genre": "",
        "rating": "",
        "release_year": "",
        "description": "",
    },
    {
        "title": "",
        "director": "",
        "genre": "",
        "rating": "",
        "release_year": "",
        "description": "",
    },
    {
        "title": "",
        "director": "",
        "genre": "",
        "rating": "",
        "release_year": "",
        "description": "",
    },
    {
        "title": "",
        "director": "",
        "genre": "",
        "rating": "",
        "release_year": "",
        "description": "",
    },
    {
        "title": "",
        "director": "",
        "genre": "",
        "rating": "",
        "release_year": "",
        "description": "",
    },
    {
        "title": "",
        "director": "",
        "genre": "",
        "rating": "",
        "release_year": "",
        "description": "",
    },
    {
        "title": "",
        "director": "",
        "genre": "",
        "rating": "",
        "release_year": "",
        "description": "",
    },
    {
        "title": "",
        "director": "",
        "genre": "",
        "rating": "",
        "release_year": "",
        "description": "",
    },
    {
        "title": "",
        "director": "",
        "genre": "",
        "rating": "",
        "release_year": "",
        "description": "",
    },
    {
        "title": "",
        "director": "",
        "genre": "",
        "rating": "",
        "release_year": "",
        "description": "",
    },
    {
        "title": "",
        "director": "",
        "genre": "",
        "rating": "",
        "release_year": "",
        "description": "",
    },
    {
        "title": "",
        "director": "",
        "genre": "",
        "rating": "",
        "release_year": "",
        "description": "",
    },
    {
        "title": "",
        "director": "",
        "genre": "",
        "rating": "",
        "release_year": "",
        "description": "",
    },
    {
        "title": "",
        "director": "",
        "genre": "",
        "rating": "",
        "release_year": "",
        "description": "",
    },
    {
        "title": "",
        "director": "",
        "genre": "",
        "rating": "",
        "release_year": "",
        "description": "",
    },
    {
        "title": "",
        "director": "",
        "genre": "",
        "rating": "",
        "release_year": "",
        "description": "",
    },
    {
        "title": "",
        "director": "",
        "genre": "",
        "rating": "",
        "release_year": "",
        "description": "",
    },



]